/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime Config */
        get: operations["runtime_config_api_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Resume */
        post: operations["ingest_resume_api_v1_resumes_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/ingest/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Resume Stream */
        post: operations["ingest_resume_stream_api_v1_resumes_ingest_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Resume */
        post: operations["analyze_resume_api_v1_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rewrites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rewrite Bullets */
        post: operations["rewrite_bullets_api_v1_rewrites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/docx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Document */
        post: operations["generate_document_api_v1_documents_docx_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdditionalSection */
        AdditionalSection: {
            /** Title */
            title: string;
            /** Items */
            items?: string[];
        };
        /** AnalysisRequest */
        AnalysisRequest: {
            resume: components["schemas"]["ResumeDocument"];
            /** Job Description */
            job_description: string;
            /** Ai Processing Consent */
            ai_processing_consent: boolean;
        };
        /** ApiError */
        ApiError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
        };
        /** Body_ingest_resume_api_v1_resumes_ingest_post */
        Body_ingest_resume_api_v1_resumes_ingest_post: {
            /** File */
            file: string;
            /** Ai Processing Consent */
            ai_processing_consent: boolean;
            /**
             * Allow Vision Fallback
             * @default false
             */
            allow_vision_fallback: boolean;
        };
        /** Body_ingest_resume_stream_api_v1_resumes_ingest_stream_post */
        Body_ingest_resume_stream_api_v1_resumes_ingest_stream_post: {
            /** File */
            file: string;
            /** Ai Processing Consent */
            ai_processing_consent: boolean;
            /**
             * Allow Vision Fallback
             * @default false
             */
            allow_vision_fallback: boolean;
        };
        /** BulletRewriteRequest */
        BulletRewriteRequest: {
            resume: components["schemas"]["ResumeDocument"];
            /** Job Description */
            job_description: string;
            /** Bullet Ids */
            bullet_ids: string[];
            /** Ai Processing Consent */
            ai_processing_consent: boolean;
        };
        /** BulletRewriteResponse */
        BulletRewriteResponse: {
            /** Items */
            items: components["schemas"]["BulletRewriteResult"][];
        };
        /** BulletRewriteResult */
        BulletRewriteResult: {
            /** Bullet Id */
            bullet_id: string;
            /** Original Text */
            original_text: string;
            /** Alternatives */
            alternatives: components["schemas"]["RewriteAlternative"][];
        };
        /** ContactInfo */
        ContactInfo: {
            /** Full Name */
            full_name: string;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Location */
            location?: string | null;
            /** Links */
            links?: string[];
        };
        /** Education */
        Education: {
            /** Institution */
            institution: string;
            /** Credential */
            credential: string;
            /** Field Of Study */
            field_of_study?: string | null;
            /** Location */
            location?: string | null;
            /** Dates */
            dates?: string | null;
            /** Details */
            details?: string[];
        };
        /**
         * ExtractionMethod
         * @enum {string}
         */
        ExtractionMethod: "pdf_text" | "docx_text" | "gemini_vision";
        /** GapAnalysis */
        GapAnalysis: {
            /** Match Score */
            match_score: number;
            /** Keyword Gaps */
            keyword_gaps?: components["schemas"]["KeywordGap"][];
            title_alignment: components["schemas"]["TitleAlignment"];
            /** Actionable Recommendations */
            actionable_recommendations: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Gemini Configured */
            gemini_configured: boolean;
        };
        /** IngestionErrorEvent */
        IngestionErrorEvent: {
            /**
             * Type
             * @default error
             * @constant
             */
            type: "error";
            error: components["schemas"]["ApiError"];
        };
        /** IngestionProgressEvent */
        IngestionProgressEvent: {
            /**
             * Type
             * @default progress
             * @constant
             */
            type: "progress";
            stage: components["schemas"]["IngestionStage"];
            /** Sequence */
            sequence: number;
            /** Message */
            message: string;
        };
        /** IngestionResultEvent */
        IngestionResultEvent: {
            /**
             * Type
             * @default result
             * @constant
             */
            type: "result";
            data: components["schemas"]["ResumeIngestionResponse"];
        };
        /**
         * IngestionStage
         * @enum {string}
         */
        IngestionStage: "parsing" | "structuring" | "validating";
        /**
         * KeywordCategory
         * @enum {string}
         */
        KeywordCategory: "technical_skill" | "tool" | "soft_skill" | "domain" | "other";
        /** KeywordGap */
        KeywordGap: {
            /** Term */
            term: string;
            category: components["schemas"]["KeywordCategory"];
            /** Importance */
            importance: string;
        };
        /** Project */
        Project: {
            /** Id */
            id?: string;
            /** Name */
            name: string;
            /** Role */
            role?: string | null;
            /** Dates */
            dates?: string | null;
            /** Link */
            link?: string | null;
            /** Bullets */
            bullets?: components["schemas"]["ResumeBullet"][];
        };
        /** ResumeBullet */
        ResumeBullet: {
            /** Text */
            text: string;
            /** Id */
            id?: string;
        };
        /** ResumeDocument */
        ResumeDocument: {
            contact: components["schemas"]["ContactInfo"];
            /** Professional Summary */
            professional_summary?: string | null;
            /** Work Experience */
            work_experience?: components["schemas"]["WorkExperience"][];
            /** Skills */
            skills?: components["schemas"]["SkillGroup"][];
            /** Education */
            education?: components["schemas"]["Education"][];
            /** Certifications */
            certifications?: string[];
            /** Projects */
            projects?: components["schemas"]["Project"][];
            /** Additional Sections */
            additional_sections?: components["schemas"]["AdditionalSection"][];
        };
        /** ResumeIngestionResponse */
        ResumeIngestionResponse: {
            resume: components["schemas"]["ResumeDocument"];
            extraction_method: components["schemas"]["ExtractionMethod"];
            /** Warnings */
            warnings?: string[];
        };
        /** RewriteAlternative */
        RewriteAlternative: {
            /** Text */
            text: string;
            /** Incorporated Keywords */
            incorporated_keywords?: string[];
        };
        /** RuntimeConfig */
        RuntimeConfig: {
            /** Max Upload Bytes */
            max_upload_bytes: number;
            /** Accepted Extensions */
            accepted_extensions: string[];
            /** Vision Fallback Available */
            vision_fallback_available: boolean;
            /** Gemini Model */
            gemini_model: string;
        };
        /** SkillGroup */
        SkillGroup: {
            /** Label */
            label?: string | null;
            /** Items */
            items?: string[];
        };
        /** TitleAlignment */
        TitleAlignment: {
            /** Target Title */
            target_title: string;
            assessment: components["schemas"]["TitleAssessment"];
            /** Rationale */
            rationale: string;
            /** Equivalent Title Suggestions */
            equivalent_title_suggestions?: string[];
        };
        /**
         * TitleAssessment
         * @enum {string}
         */
        TitleAssessment: "aligned" | "partially_aligned" | "not_aligned";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkExperience */
        WorkExperience: {
            /** Id */
            id?: string;
            /** Employer */
            employer: string;
            /** Title */
            title: string;
            /** Location */
            location?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Bullets */
            bullets?: components["schemas"]["ResumeBullet"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    runtime_config_api_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeConfig"];
                };
            };
        };
    };
    ingest_resume_api_v1_resumes_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_resume_api_v1_resumes_ingest_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeIngestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_resume_stream_api_v1_resumes_ingest_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_resume_stream_api_v1_resumes_ingest_stream_post"];
            };
        };
        responses: {
            /** @description One IngestionStreamEvent per JSON Lines record. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/jsonl": components["schemas"]["IngestionProgressEvent"] | components["schemas"]["IngestionResultEvent"] | components["schemas"]["IngestionErrorEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_resume_api_v1_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GapAnalysis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rewrite_bullets_api_v1_rewrites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulletRewriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulletRewriteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_document_api_v1_documents_docx_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeDocument"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
